<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_about-content',
		'title' => 'About Content',
		'fields' => array (
			array (
				'key' => 'field_554bded565d49',
				'label' => 'Different Content',
				'name' => 'about_flexible_content',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Team',
						'name' => 'about_our_team',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_554bdf0a65d4a',
								'label' => 'Team',
								'name' => 'about_our_team_repeater',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_554bdf4665d4c',
										'label' => 'Name',
										'name' => 'about_our_team_repeater_name',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_554bdf5265d4d',
										'label' => 'Image',
										'name' => 'about_our_team_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
									),
									array (
										'key' => 'field_554bdf5f65d4e',
										'label' => 'Social Icons',
										'name' => 'about_our_team_repeater_icons',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_554bdf7a65d4f',
												'label' => 'Link',
												'name' => 'about_our_team_repeater_icons_link',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_554bdf8465d50',
												'label' => 'Icon',
												'name' => 'about_our_team_repeater_icons_icon',
												'type' => 'font-awesome',
												'column_width' => '',
												'default_value' => 'null',
												'save_format' => 'class',
												'allow_null' => 0,
												'enqueue_fa' => 0,
												'choices' => array (
													'fa-adjust' => '',
													'fa-adn' => '',
													'fa-align-center' => '',
													'fa-align-justify' => '',
													'fa-align-left' => '',
													'fa-align-right' => '',
													'fa-ambulance' => '',
													'fa-anchor' => '',
													'fa-android' => '',
													'fa-angle-double-down' => '',
													'fa-angle-double-left' => '',
													'fa-angle-double-right' => '',
													'fa-angle-double-up' => '',
													'fa-angle-down' => '',
													'fa-angle-left' => '',
													'fa-angle-right' => '',
													'fa-angle-up' => '',
													'fa-apple' => '',
													'fa-archive' => '',
													'fa-arrow-circle-down' => '',
													'fa-arrow-circle-left' => '',
													'fa-arrow-circle-o-down' => '',
													'fa-arrow-circle-o-left' => '',
													'fa-arrow-circle-o-right' => '',
													'fa-arrow-circle-o-up' => '',
													'fa-arrow-circle-right' => '',
													'fa-arrow-circle-up' => '',
													'fa-arrow-down' => '',
													'fa-arrow-left' => '',
													'fa-arrow-right' => '',
													'fa-arrow-up' => '',
													'fa-arrows' => '',
													'fa-arrows-alt' => '',
													'fa-arrows-h' => '',
													'fa-arrows-v' => '',
													'fa-asterisk' => '',
													'fa-automobile' => '',
													'fa-backward' => '',
													'fa-ban' => '',
													'fa-bank' => '',
													'fa-bar-chart-o' => '',
													'fa-barcode' => '',
													'fa-bars' => '',
													'fa-beer' => '',
													'fa-behance' => '',
													'fa-behance-square' => '',
													'fa-bell' => '',
													'fa-bell-o' => '',
													'fa-bitbucket' => '',
													'fa-bitbucket-square' => '',
													'fa-bitcoin' => '',
													'fa-bold' => '',
													'fa-bolt' => '',
													'fa-bomb' => '',
													'fa-book' => '',
													'fa-bookmark' => '',
													'fa-bookmark-o' => '',
													'fa-briefcase' => '',
													'fa-btc' => '',
													'fa-bug' => '',
													'fa-building' => '',
													'fa-building-o' => '',
													'fa-bullhorn' => '',
													'fa-bullseye' => '',
													'fa-cab' => '',
													'fa-calendar' => '',
													'fa-calendar-o' => '',
													'fa-camera' => '',
													'fa-camera-retro' => '',
													'fa-car' => '',
													'fa-caret-down' => '',
													'fa-caret-left' => '',
													'fa-caret-right' => '',
													'fa-caret-square-o-down' => '',
													'fa-caret-square-o-left' => '',
													'fa-caret-square-o-right' => '',
													'fa-caret-square-o-up' => '',
													'fa-caret-up' => '',
													'fa-certificate' => '',
													'fa-chain' => '',
													'fa-chain-broken' => '',
													'fa-check' => '',
													'fa-check-circle' => '',
													'fa-check-circle-o' => '',
													'fa-check-square' => '',
													'fa-check-square-o' => '',
													'fa-chevron-circle-down' => '',
													'fa-chevron-circle-left' => '',
													'fa-chevron-circle-right' => '',
													'fa-chevron-circle-up' => '',
													'fa-chevron-down' => '',
													'fa-chevron-left' => '',
													'fa-chevron-right' => '',
													'fa-chevron-up' => '',
													'fa-child' => '',
													'fa-circle' => '',
													'fa-circle-o' => '',
													'fa-circle-o-notch' => '',
													'fa-circle-thin' => '',
													'fa-clipboard' => '',
													'fa-clock-o' => '',
													'fa-cloud' => '',
													'fa-cloud-download' => '',
													'fa-cloud-upload' => '',
													'fa-cny' => '',
													'fa-code' => '',
													'fa-code-fork' => '',
													'fa-codepen' => '',
													'fa-coffee' => '',
													'fa-cog' => '',
													'fa-cogs' => '',
													'fa-columns' => '',
													'fa-comment' => '',
													'fa-comment-o' => '',
													'fa-comments' => '',
													'fa-comments-o' => '',
													'fa-compass' => '',
													'fa-compress' => '',
													'fa-copy' => '',
													'fa-credit-card' => '',
													'fa-crop' => '',
													'fa-crosshairs' => '',
													'fa-css3' => '',
													'fa-cube' => '',
													'fa-cubes' => '',
													'fa-cut' => '',
													'fa-cutlery' => '',
													'fa-dashboard' => '',
													'fa-database' => '',
													'fa-dedent' => '',
													'fa-delicious' => '',
													'fa-desktop' => '',
													'fa-deviantart' => '',
													'fa-digg' => '',
													'fa-dollar' => '',
													'fa-dot-circle-o' => '',
													'fa-download' => '',
													'fa-dribbble' => '',
													'fa-dropbox' => '',
													'fa-drupal' => '',
													'fa-edit' => '',
													'fa-eject' => '',
													'fa-ellipsis-h' => '',
													'fa-ellipsis-v' => '',
													'fa-empire' => '',
													'fa-envelope' => '',
													'fa-envelope-o' => '',
													'fa-envelope-square' => '',
													'fa-eraser' => '',
													'fa-eur' => '',
													'fa-euro' => '',
													'fa-exchange' => '',
													'fa-exclamation' => '',
													'fa-exclamation-circle' => '',
													'fa-exclamation-triangle' => '',
													'fa-expand' => '',
													'fa-external-link' => '',
													'fa-external-link-square' => '',
													'fa-eye' => '',
													'fa-eye-slash' => '',
													'fa-facebook' => '',
													'fa-facebook-square' => '',
													'fa-fast-backward' => '',
													'fa-fast-forward' => '',
													'fa-fax' => '',
													'fa-female' => '',
													'fa-fighter-jet' => '',
													'fa-file' => '',
													'fa-file-archive-o' => '',
													'fa-file-audio-o' => '',
													'fa-file-code-o' => '',
													'fa-file-excel-o' => '',
													'fa-file-image-o' => '',
													'fa-file-movie-o' => '',
													'fa-file-o' => '',
													'fa-file-pdf-o' => '',
													'fa-file-photo-o' => '',
													'fa-file-picture-o' => '',
													'fa-file-powerpoint-o' => '',
													'fa-file-sound-o' => '',
													'fa-file-text' => '',
													'fa-file-text-o' => '',
													'fa-file-video-o' => '',
													'fa-file-word-o' => '',
													'fa-file-zip-o' => '',
													'fa-files-o' => '',
													'fa-film' => '',
													'fa-filter' => '',
													'fa-fire' => '',
													'fa-fire-extinguisher' => '',
													'fa-flag' => '',
													'fa-flag-checkered' => '',
													'fa-flag-o' => '',
													'fa-flash' => '',
													'fa-flask' => '',
													'fa-flickr' => '',
													'fa-floppy-o' => '',
													'fa-folder' => '',
													'fa-folder-o' => '',
													'fa-folder-open' => '',
													'fa-folder-open-o' => '',
													'fa-font' => '',
													'fa-forward' => '',
													'fa-foursquare' => '',
													'fa-frown-o' => '',
													'fa-gamepad' => '',
													'fa-gavel' => '',
													'fa-gbp' => '',
													'fa-ge' => '',
													'fa-gear' => '',
													'fa-gears' => '',
													'fa-gift' => '',
													'fa-git' => '',
													'fa-git-square' => '',
													'fa-github' => '',
													'fa-github-alt' => '',
													'fa-github-square' => '',
													'fa-gittip' => '',
													'fa-glass' => '',
													'fa-globe' => '',
													'fa-google' => '',
													'fa-google-plus' => '',
													'fa-google-plus-square' => '',
													'fa-graduation-cap' => '',
													'fa-group' => '',
													'fa-h-square' => '',
													'fa-hacker-news' => '',
													'fa-hand-o-down' => '',
													'fa-hand-o-left' => '',
													'fa-hand-o-right' => '',
													'fa-hand-o-up' => '',
													'fa-hdd-o' => '',
													'fa-header' => '',
													'fa-headphones' => '',
													'fa-heart' => '',
													'fa-heart-o' => '',
													'fa-history' => '',
													'fa-home' => '',
													'fa-hospital-o' => '',
													'fa-html5' => '',
													'fa-image' => '',
													'fa-inbox' => '',
													'fa-indent' => '',
													'fa-info' => '',
													'fa-info-circle' => '',
													'fa-inr' => '',
													'fa-instagram' => '',
													'fa-institution' => '',
													'fa-italic' => '',
													'fa-joomla' => '',
													'fa-jpy' => '',
													'fa-jsfiddle' => '',
													'fa-key' => '',
													'fa-keyboard-o' => '',
													'fa-krw' => '',
													'fa-language' => '',
													'fa-laptop' => '',
													'fa-leaf' => '',
													'fa-legal' => '',
													'fa-lemon-o' => '',
													'fa-level-down' => '',
													'fa-level-up' => '',
													'fa-life-bouy' => '',
													'fa-life-ring' => '',
													'fa-life-saver' => '',
													'fa-lightbulb-o' => '',
													'fa-link' => '',
													'fa-linkedin' => '',
													'fa-linkedin-square' => '',
													'fa-linux' => '',
													'fa-list' => '',
													'fa-list-alt' => '',
													'fa-list-ol' => '',
													'fa-list-ul' => '',
													'fa-location-arrow' => '',
													'fa-lock' => '',
													'fa-long-arrow-down' => '',
													'fa-long-arrow-left' => '',
													'fa-long-arrow-right' => '',
													'fa-long-arrow-up' => '',
													'fa-magic' => '',
													'fa-magnet' => '',
													'fa-mail-forward' => '',
													'fa-mail-reply' => '',
													'fa-mail-reply-all' => '',
													'fa-male' => '',
													'fa-map-marker' => '',
													'fa-maxcdn' => '',
													'fa-medkit' => '',
													'fa-meh-o' => '',
													'fa-microphone' => '',
													'fa-microphone-slash' => '',
													'fa-minus' => '',
													'fa-minus-circle' => '',
													'fa-minus-square' => '',
													'fa-minus-square-o' => '',
													'fa-mobile' => '',
													'fa-mobile-phone' => '',
													'fa-money' => '',
													'fa-moon-o' => '',
													'fa-mortar-board' => '',
													'fa-music' => '',
													'fa-navicon' => '',
													'fa-openid' => '',
													'fa-outdent' => '',
													'fa-pagelines' => '',
													'fa-paper-plane' => '',
													'fa-paper-plane-o' => '',
													'fa-paperclip' => '',
													'fa-paragraph' => '',
													'fa-paste' => '',
													'fa-pause' => '',
													'fa-paw' => '',
													'fa-pencil' => '',
													'fa-pencil-square' => '',
													'fa-pencil-square-o' => '',
													'fa-phone' => '',
													'fa-phone-square' => '',
													'fa-photo' => '',
													'fa-picture-o' => '',
													'fa-pied-piper' => '',
													'fa-pied-piper-alt' => '',
													'fa-pied-piper-square' => '',
													'fa-pinterest' => '',
													'fa-pinterest-square' => '',
													'fa-plane' => '',
													'fa-play' => '',
													'fa-play-circle' => '',
													'fa-play-circle-o' => '',
													'fa-plus' => '',
													'fa-plus-circle' => '',
													'fa-plus-square' => '',
													'fa-plus-square-o' => '',
													'fa-power-off' => '',
													'fa-print' => '',
													'fa-puzzle-piece' => '',
													'fa-qq' => '',
													'fa-qrcode' => '',
													'fa-question' => '',
													'fa-question-circle' => '',
													'fa-quote-left' => '',
													'fa-quote-right' => '',
													'fa-ra' => '',
													'fa-random' => '',
													'fa-rebel' => '',
													'fa-recycle' => '',
													'fa-reddit' => '',
													'fa-reddit-square' => '',
													'fa-refresh' => '',
													'fa-renren' => '',
													'fa-reorder' => '',
													'fa-repeat' => '',
													'fa-reply' => '',
													'fa-reply-all' => '',
													'fa-retweet' => '',
													'fa-rmb' => '',
													'fa-road' => '',
													'fa-rocket' => '',
													'fa-rotate-left' => '',
													'fa-rotate-right' => '',
													'fa-rouble' => '',
													'fa-rss' => '',
													'fa-rss-square' => '',
													'fa-rub' => '',
													'fa-ruble' => '',
													'fa-rupee' => '',
													'fa-save' => '',
													'fa-scissors' => '',
													'fa-search' => '',
													'fa-search-minus' => '',
													'fa-search-plus' => '',
													'fa-send' => '',
													'fa-send-o' => '',
													'fa-share' => '',
													'fa-share-alt' => '',
													'fa-share-alt-square' => '',
													'fa-share-square' => '',
													'fa-share-square-o' => '',
													'fa-shield' => '',
													'fa-shopping-cart' => '',
													'fa-sign-in' => '',
													'fa-sign-out' => '',
													'fa-signal' => '',
													'fa-sitemap' => '',
													'fa-skype' => '',
													'fa-slack' => '',
													'fa-sliders' => '',
													'fa-smile-o' => '',
													'fa-sort' => '',
													'fa-sort-alpha-asc' => '',
													'fa-sort-alpha-desc' => '',
													'fa-sort-amount-asc' => '',
													'fa-sort-amount-desc' => '',
													'fa-sort-asc' => '',
													'fa-sort-desc' => '',
													'fa-sort-down' => '',
													'fa-sort-numeric-asc' => '',
													'fa-sort-numeric-desc' => '',
													'fa-sort-up' => '',
													'fa-soundcloud' => '',
													'fa-space-shuttle' => '',
													'fa-spinner' => '',
													'fa-spoon' => '',
													'fa-spotify' => '',
													'fa-square' => '',
													'fa-square-o' => '',
													'fa-stack-exchange' => '',
													'fa-stack-overflow' => '',
													'fa-star' => '',
													'fa-star-half' => '',
													'fa-star-half-empty' => '',
													'fa-star-half-full' => '',
													'fa-star-half-o' => '',
													'fa-star-o' => '',
													'fa-steam' => '',
													'fa-steam-square' => '',
													'fa-step-backward' => '',
													'fa-step-forward' => '',
													'fa-stethoscope' => '',
													'fa-stop' => '',
													'fa-strikethrough' => '',
													'fa-stumbleupon' => '',
													'fa-stumbleupon-circle' => '',
													'fa-subscript' => '',
													'fa-suitcase' => '',
													'fa-sun-o' => '',
													'fa-superscript' => '',
													'fa-support' => '',
													'fa-table' => '',
													'fa-tablet' => '',
													'fa-tachometer' => '',
													'fa-tag' => '',
													'fa-tags' => '',
													'fa-tasks' => '',
													'fa-taxi' => '',
													'fa-tencent-weibo' => '',
													'fa-terminal' => '',
													'fa-text-height' => '',
													'fa-text-width' => '',
													'fa-th' => '',
													'fa-th-large' => '',
													'fa-th-list' => '',
													'fa-thumb-tack' => '',
													'fa-thumbs-down' => '',
													'fa-thumbs-o-down' => '',
													'fa-thumbs-o-up' => '',
													'fa-thumbs-up' => '',
													'fa-ticket' => '',
													'fa-times' => '',
													'fa-times-circle' => '',
													'fa-times-circle-o' => '',
													'fa-tint' => '',
													'fa-toggle-down' => '',
													'fa-toggle-left' => '',
													'fa-toggle-right' => '',
													'fa-toggle-up' => '',
													'fa-trash-o' => '',
													'fa-tree' => '',
													'fa-trello' => '',
													'fa-trophy' => '',
													'fa-truck' => '',
													'fa-try' => '',
													'fa-tumblr' => '',
													'fa-tumblr-square' => '',
													'fa-turkish-lira' => '',
													'fa-twitter' => '',
													'fa-twitter-square' => '',
													'fa-umbrella' => '',
													'fa-underline' => '',
													'fa-undo' => '',
													'fa-university' => '',
													'fa-unlink' => '',
													'fa-unlock' => '',
													'fa-unlock-alt' => '',
													'fa-unsorted' => '',
													'fa-upload' => '',
													'fa-usd' => '',
													'fa-user' => '',
													'fa-user-md' => '',
													'fa-users' => '',
													'fa-video-camera' => '',
													'fa-vimeo-square' => '',
													'fa-vine' => '',
													'fa-vk' => '',
													'fa-volume-down' => '',
													'fa-volume-off' => '',
													'fa-volume-up' => '',
													'fa-warning' => '',
													'fa-wechat' => '',
													'fa-weibo' => '',
													'fa-weixin' => '',
													'fa-wheelchair' => '',
													'fa-windows' => '',
													'fa-won' => '',
													'fa-wordpress' => '',
													'fa-wrench' => '',
													'fa-xing' => '',
													'fa-xing-square' => '',
													'fa-yahoo' => '',
													'fa-yen' => '',
													'fa-youtube' => '',
													'fa-youtube-play' => '',
													'fa-youtube-square' => '',
												),
											),
										),
										'row_min' => 0,
										'row_limit' => '',
										'layout' => 'table',
										'button_label' => 'Add a member',
									),
								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add a member',
							),
						),
					),
					array (
						'label' => 'Clients',
						'name' => 'about_clients',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_554bdfa265d53',
								'label' => 'Clients',
								'name' => 'about_clients_repeater',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_554bdfcc65d54',
										'label' => 'Image',
										'name' => 'about_clients_repeater_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
									),
									array (
										'key' => 'field_559e92b61d147',
										'label' => 'Link',
										'name' => 'about_clients_repeater_image_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),

								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add a client',
							),
						),
					),
				),
				'button_label' => 'Add team or clients',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_about-intro-image',
		'title' => 'About Intro Image',
		'fields' => array (
			array (
				'key' => 'field_555a5e7511b84',
				'label' => 'Image',
				'name' => 'about_intro_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_555a5e8311b85',
				'label' => 'Title',
				'name' => 'about_intro_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5e8a11b86',
				'label' => 'Content',
				'name' => 'about_intro_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_about-settings',
		'title' => 'About Settings',
		'fields' => array (
			array (
				'key' => 'field_555a5dcc62725',
				'label' => 'Title',
				'name' => 'about_after_intro_content_title',
				'type' => 'text',
				'instructions' => 'Title in the up left side.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5df462726',
				'label' => 'Short content',
				'name' => 'about_after_intro_content_short_content',
				'type' => 'text',
				'instructions' => 'Content in the bottom left side.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5e0062727',
				'label' => 'Full content',
				'name' => 'about_after_intro_content_full_content',
				'type' => 'wysiwyg',
				'instructions' => 'Full content in the right side.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_555a5e1a62728',
				'label' => 'Hide Content',
				'name' => 'about_after_intro_content_hide',
				'type' => 'select',
				'instructions' => 'Hide or Show this content. Default is Hide.',
				'choices' => array (
					1 => 'Hide',
					2 => 'Show',
				),
				'default_value' => 1,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog-settings',
		'title' => 'Blog Settings',
		'fields' => array (
			array (
				'key' => 'field_555a5d925b413',
				'label' => 'Blog Category',
				'name' => 'blog_post_category',
				'type' => 'taxonomy',
				'instructions' => 'Select the category where you want to get the posts.',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-blog.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_bx-slider',
		'title' => 'BX Slider',
		'fields' => array (
			array (
				'key' => 'field_554bdd5f9d91e',
				'label' => 'Gallery',
				'name' => 'bxslider_repeater',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_554bdd979d91f',
						'label' => 'Image',
						'name' => 'bxslider_repeater_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_554bdda69d920',
						'label' => 'Title',
						'name' => 'bxslider_repeater_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_554bddb99d921',
						'label' => 'Description',
						'name' => 'bxslider_repeater_under_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add an image',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-bx_slider.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_codrops-slider',
		'title' => 'Codrops Slider',
		'fields' => array (
			array (
				'key' => 'field_555a5cd39097c',
				'label' => 'Title',
				'name' => 'home_slider_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5cdf9097d',
				'label' => 'Description',
				'name' => 'home_slider_description',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5cf2c5f28',
				'label' => 'Slider Content',
				'name' => 'home_slider_gallery',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_555a5d0cc5f29',
						'label' => 'Images',
						'name' => 'home_slider_gallery_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add an image',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-slider_home.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact-settings',
		'title' => 'Contact Settings',
		'fields' => array (
			array (
				'key' => 'field_555a5bd0c6b4e',
				'label' => 'Contact Form',
				'name' => 'contact_form',
				'type' => 'acf_cf7',
				'allow_null' => 0,
				'multiple' => 0,
				'disable' => array (
					0 => 0,
				),
			),
			array (
				'key' => 'field_555a5beb98f3e',
				'label' => 'Google Map',
				'name' => 'google_map',
				'type' => 'true_false',
				'instructions' => 'If checked, a Google map will be shown above the page\'s content with the location info below.',
				'message' => 'Google Map',
				'default_value' => 0,
			),
			array (
				'key' => 'field_555a5c0008d22',
				'label' => 'Latitude',
				'name' => 'map_latitude',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555a5beb98f3e',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5c0d08d23',
				'label' => 'Longtitude',
				'name' => 'map_longtitude',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555a5beb98f3e',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5c2317ab1',
				'label' => 'Street Adress',
				'name' => 'contact_street_adress',
				'type' => 'text',
				'default_value' => '<i class="fa fa-map-marker"></i>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5c401f3e5',
				'label' => 'Phone Number',
				'name' => 'contact_phone_number',
				'type' => 'text',
				'default_value' => '<i class="fa fa-phone"></i',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5c4d1f3e6',
				'label' => 'Email Adress',
				'name' => 'contact_email_adress',
				'type' => 'text',
				'default_value' => '<i class="fa fa-envelope"></i>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a5c5db22b6',
				'label' => 'Opening Hours',
				'name' => 'contact_opening_hours',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer-settings',
		'title' => 'Footer Settings',
		'fields' => array (
			array (
				'key' => 'field_555a5b4fcb7d6',
				'label' => 'Social Links',
				'name' => 'social_links',
				'type' => 'repeater',
				'instructions' => 'In footer, social links works as icons in the left you write the link and in the right the name of social page. If you want to add click Add another social media.',
				'sub_fields' => array (
					array (
						'key' => 'field_555a5b78cb7d7',
						'label' => 'Name',
						'name' => 'social_links_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_555a5b81cb7d8',
						'label' => 'Link',
						'name' => 'social_links_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add social media',
			),
			array (
				'key' => 'field_555a5b8d20aff',
				'label' => 'Footer Image',
				'name' => 'footer_image',
				'type' => 'image',
				'instructions' => 'Add a background image to your footer.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_555a5b9c857eb',
				'label' => 'Copyright',
				'name' => 'footer_copyright',
				'type' => 'text',
				'instructions' => 'Add your copyright to the page.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-footer',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_general-settings',
		'title' => 'General Settings',
		'fields' => array (
			array (
				'key' => 'field_555a59b0b443c',
				'label' => 'Main Color',
				'name' => 'main_color',
				'type' => 'color_picker',
				'instructions' => 'Select the main color of the website, which will override all the elements\' main colors.',
				'default_value' => '',
			),
			array (
				'key' => 'field_555a59cc71d63',
				'label' => 'Loader color',
				'name' => 'loader_color',
				'type' => 'color_picker',
				'instructions' => 'Change color of loader, default color is from upper field.',
				'default_value' => '',
			),
			array (
				'key' => 'field_555a59df95c41',
				'label' => 'Favicon of the site',
				'name' => 'favicon_of_site',
				'type' => 'image',
				'instructions' => 'If you have any favicon, which is in the title top to browser, upload here.',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_555a59f9f8f3d',
				'label' => 'General logo',
				'name' => 'image_logo',
				'type' => 'image',
				'instructions' => 'Logo in up left for all pages.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_header-settings',
		'title' => 'Header Settings',
		'fields' => array (
			array (
				'key' => 'field_555a58dcf66d8',
				'label' => 'Logo',
				'name' => 'white_logo_header',
				'type' => 'image',
				'instructions' => 'Upload your logo in header. Be carefully the background is black.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_555a58fd5e514',
				'label' => 'Fixed Header',
				'name' => 'fixed_header',
				'type' => 'true_false',
				'instructions' => 'If you tick this option, your choosen header will be fixed.',
				'message' => 'Fixed Header',
				'default_value' => 0,
			),
			array (
				'key' => 'field_555a5914db277',
				'label' => 'Header Type',
				'name' => 'header_type',
				'type' => 'radio',
				'instructions' => 'Choose your header layout, check in demo for examples or in presentation.',
				'choices' => array (
					1 => 'Default',
					2 => 'Classic',
					3 => 'Wide',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_555a59623fc25',
				'label' => 'Social Icons',
				'name' => 'social_icons',
				'type' => 'repeater',
				'instructions' => 'Add icons in the header, you can add as many as you want.',
				'sub_fields' => array (
					array (
						'key' => 'field_555a597e3fc26',
						'label' => 'Link',
						'name' => 'social_icons_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_555a598a3fc27',
						'label' => 'Icon',
						'name' => 'social_icons_icon',
						'type' => 'font-awesome',
						'column_width' => '',
						'default_value' => 'null',
						'save_format' => 'class',
						'allow_null' => 0,
						'enqueue_fa' => 0,
						'choices' => array (
							'fa-adjust' => '',
							'fa-adn' => '',
							'fa-align-center' => '',
							'fa-align-justify' => '',
							'fa-align-left' => '',
							'fa-align-right' => '',
							'fa-ambulance' => '',
							'fa-anchor' => '',
							'fa-android' => '',
							'fa-angle-double-down' => '',
							'fa-angle-double-left' => '',
							'fa-angle-double-right' => '',
							'fa-angle-double-up' => '',
							'fa-angle-down' => '',
							'fa-angle-left' => '',
							'fa-angle-right' => '',
							'fa-angle-up' => '',
							'fa-apple' => '',
							'fa-archive' => '',
							'fa-arrow-circle-down' => '',
							'fa-arrow-circle-left' => '',
							'fa-arrow-circle-o-down' => '',
							'fa-arrow-circle-o-left' => '',
							'fa-arrow-circle-o-right' => '',
							'fa-arrow-circle-o-up' => '',
							'fa-arrow-circle-right' => '',
							'fa-arrow-circle-up' => '',
							'fa-arrow-down' => '',
							'fa-arrow-left' => '',
							'fa-arrow-right' => '',
							'fa-arrow-up' => '',
							'fa-arrows' => '',
							'fa-arrows-alt' => '',
							'fa-arrows-h' => '',
							'fa-arrows-v' => '',
							'fa-asterisk' => '',
							'fa-automobile' => '',
							'fa-backward' => '',
							'fa-ban' => '',
							'fa-bank' => '',
							'fa-bar-chart-o' => '',
							'fa-barcode' => '',
							'fa-bars' => '',
							'fa-beer' => '',
							'fa-behance' => '',
							'fa-behance-square' => '',
							'fa-bell' => '',
							'fa-bell-o' => '',
							'fa-bitbucket' => '',
							'fa-bitbucket-square' => '',
							'fa-bitcoin' => '',
							'fa-bold' => '',
							'fa-bolt' => '',
							'fa-bomb' => '',
							'fa-book' => '',
							'fa-bookmark' => '',
							'fa-bookmark-o' => '',
							'fa-briefcase' => '',
							'fa-btc' => '',
							'fa-bug' => '',
							'fa-building' => '',
							'fa-building-o' => '',
							'fa-bullhorn' => '',
							'fa-bullseye' => '',
							'fa-cab' => '',
							'fa-calendar' => '',
							'fa-calendar-o' => '',
							'fa-camera' => '',
							'fa-camera-retro' => '',
							'fa-car' => '',
							'fa-caret-down' => '',
							'fa-caret-left' => '',
							'fa-caret-right' => '',
							'fa-caret-square-o-down' => '',
							'fa-caret-square-o-left' => '',
							'fa-caret-square-o-right' => '',
							'fa-caret-square-o-up' => '',
							'fa-caret-up' => '',
							'fa-certificate' => '',
							'fa-chain' => '',
							'fa-chain-broken' => '',
							'fa-check' => '',
							'fa-check-circle' => '',
							'fa-check-circle-o' => '',
							'fa-check-square' => '',
							'fa-check-square-o' => '',
							'fa-chevron-circle-down' => '',
							'fa-chevron-circle-left' => '',
							'fa-chevron-circle-right' => '',
							'fa-chevron-circle-up' => '',
							'fa-chevron-down' => '',
							'fa-chevron-left' => '',
							'fa-chevron-right' => '',
							'fa-chevron-up' => '',
							'fa-child' => '',
							'fa-circle' => '',
							'fa-circle-o' => '',
							'fa-circle-o-notch' => '',
							'fa-circle-thin' => '',
							'fa-clipboard' => '',
							'fa-clock-o' => '',
							'fa-cloud' => '',
							'fa-cloud-download' => '',
							'fa-cloud-upload' => '',
							'fa-cny' => '',
							'fa-code' => '',
							'fa-code-fork' => '',
							'fa-codepen' => '',
							'fa-coffee' => '',
							'fa-cog' => '',
							'fa-cogs' => '',
							'fa-columns' => '',
							'fa-comment' => '',
							'fa-comment-o' => '',
							'fa-comments' => '',
							'fa-comments-o' => '',
							'fa-compass' => '',
							'fa-compress' => '',
							'fa-copy' => '',
							'fa-credit-card' => '',
							'fa-crop' => '',
							'fa-crosshairs' => '',
							'fa-css3' => '',
							'fa-cube' => '',
							'fa-cubes' => '',
							'fa-cut' => '',
							'fa-cutlery' => '',
							'fa-dashboard' => '',
							'fa-database' => '',
							'fa-dedent' => '',
							'fa-delicious' => '',
							'fa-desktop' => '',
							'fa-deviantart' => '',
							'fa-digg' => '',
							'fa-dollar' => '',
							'fa-dot-circle-o' => '',
							'fa-download' => '',
							'fa-dribbble' => '',
							'fa-dropbox' => '',
							'fa-drupal' => '',
							'fa-edit' => '',
							'fa-eject' => '',
							'fa-ellipsis-h' => '',
							'fa-ellipsis-v' => '',
							'fa-empire' => '',
							'fa-envelope' => '',
							'fa-envelope-o' => '',
							'fa-envelope-square' => '',
							'fa-eraser' => '',
							'fa-eur' => '',
							'fa-euro' => '',
							'fa-exchange' => '',
							'fa-exclamation' => '',
							'fa-exclamation-circle' => '',
							'fa-exclamation-triangle' => '',
							'fa-expand' => '',
							'fa-external-link' => '',
							'fa-external-link-square' => '',
							'fa-eye' => '',
							'fa-eye-slash' => '',
							'fa-facebook' => '',
							'fa-facebook-square' => '',
							'fa-fast-backward' => '',
							'fa-fast-forward' => '',
							'fa-fax' => '',
							'fa-female' => '',
							'fa-fighter-jet' => '',
							'fa-file' => '',
							'fa-file-archive-o' => '',
							'fa-file-audio-o' => '',
							'fa-file-code-o' => '',
							'fa-file-excel-o' => '',
							'fa-file-image-o' => '',
							'fa-file-movie-o' => '',
							'fa-file-o' => '',
							'fa-file-pdf-o' => '',
							'fa-file-photo-o' => '',
							'fa-file-picture-o' => '',
							'fa-file-powerpoint-o' => '',
							'fa-file-sound-o' => '',
							'fa-file-text' => '',
							'fa-file-text-o' => '',
							'fa-file-video-o' => '',
							'fa-file-word-o' => '',
							'fa-file-zip-o' => '',
							'fa-files-o' => '',
							'fa-film' => '',
							'fa-filter' => '',
							'fa-fire' => '',
							'fa-fire-extinguisher' => '',
							'fa-flag' => '',
							'fa-flag-checkered' => '',
							'fa-flag-o' => '',
							'fa-flash' => '',
							'fa-flask' => '',
							'fa-flickr' => '',
							'fa-floppy-o' => '',
							'fa-folder' => '',
							'fa-folder-o' => '',
							'fa-folder-open' => '',
							'fa-folder-open-o' => '',
							'fa-font' => '',
							'fa-forward' => '',
							'fa-foursquare' => '',
							'fa-frown-o' => '',
							'fa-gamepad' => '',
							'fa-gavel' => '',
							'fa-gbp' => '',
							'fa-ge' => '',
							'fa-gear' => '',
							'fa-gears' => '',
							'fa-gift' => '',
							'fa-git' => '',
							'fa-git-square' => '',
							'fa-github' => '',
							'fa-github-alt' => '',
							'fa-github-square' => '',
							'fa-gittip' => '',
							'fa-glass' => '',
							'fa-globe' => '',
							'fa-google' => '',
							'fa-google-plus' => '',
							'fa-google-plus-square' => '',
							'fa-graduation-cap' => '',
							'fa-group' => '',
							'fa-h-square' => '',
							'fa-hacker-news' => '',
							'fa-hand-o-down' => '',
							'fa-hand-o-left' => '',
							'fa-hand-o-right' => '',
							'fa-hand-o-up' => '',
							'fa-hdd-o' => '',
							'fa-header' => '',
							'fa-headphones' => '',
							'fa-heart' => '',
							'fa-heart-o' => '',
							'fa-history' => '',
							'fa-home' => '',
							'fa-hospital-o' => '',
							'fa-html5' => '',
							'fa-image' => '',
							'fa-inbox' => '',
							'fa-indent' => '',
							'fa-info' => '',
							'fa-info-circle' => '',
							'fa-inr' => '',
							'fa-instagram' => '',
							'fa-institution' => '',
							'fa-italic' => '',
							'fa-joomla' => '',
							'fa-jpy' => '',
							'fa-jsfiddle' => '',
							'fa-key' => '',
							'fa-keyboard-o' => '',
							'fa-krw' => '',
							'fa-language' => '',
							'fa-laptop' => '',
							'fa-leaf' => '',
							'fa-legal' => '',
							'fa-lemon-o' => '',
							'fa-level-down' => '',
							'fa-level-up' => '',
							'fa-life-bouy' => '',
							'fa-life-ring' => '',
							'fa-life-saver' => '',
							'fa-lightbulb-o' => '',
							'fa-link' => '',
							'fa-linkedin' => '',
							'fa-linkedin-square' => '',
							'fa-linux' => '',
							'fa-list' => '',
							'fa-list-alt' => '',
							'fa-list-ol' => '',
							'fa-list-ul' => '',
							'fa-location-arrow' => '',
							'fa-lock' => '',
							'fa-long-arrow-down' => '',
							'fa-long-arrow-left' => '',
							'fa-long-arrow-right' => '',
							'fa-long-arrow-up' => '',
							'fa-magic' => '',
							'fa-magnet' => '',
							'fa-mail-forward' => '',
							'fa-mail-reply' => '',
							'fa-mail-reply-all' => '',
							'fa-male' => '',
							'fa-map-marker' => '',
							'fa-maxcdn' => '',
							'fa-medkit' => '',
							'fa-meh-o' => '',
							'fa-microphone' => '',
							'fa-microphone-slash' => '',
							'fa-minus' => '',
							'fa-minus-circle' => '',
							'fa-minus-square' => '',
							'fa-minus-square-o' => '',
							'fa-mobile' => '',
							'fa-mobile-phone' => '',
							'fa-money' => '',
							'fa-moon-o' => '',
							'fa-mortar-board' => '',
							'fa-music' => '',
							'fa-navicon' => '',
							'fa-openid' => '',
							'fa-outdent' => '',
							'fa-pagelines' => '',
							'fa-paper-plane' => '',
							'fa-paper-plane-o' => '',
							'fa-paperclip' => '',
							'fa-paragraph' => '',
							'fa-paste' => '',
							'fa-pause' => '',
							'fa-paw' => '',
							'fa-pencil' => '',
							'fa-pencil-square' => '',
							'fa-pencil-square-o' => '',
							'fa-phone' => '',
							'fa-phone-square' => '',
							'fa-photo' => '',
							'fa-picture-o' => '',
							'fa-pied-piper' => '',
							'fa-pied-piper-alt' => '',
							'fa-pied-piper-square' => '',
							'fa-pinterest' => '',
							'fa-pinterest-square' => '',
							'fa-plane' => '',
							'fa-play' => '',
							'fa-play-circle' => '',
							'fa-play-circle-o' => '',
							'fa-plus' => '',
							'fa-plus-circle' => '',
							'fa-plus-square' => '',
							'fa-plus-square-o' => '',
							'fa-power-off' => '',
							'fa-print' => '',
							'fa-puzzle-piece' => '',
							'fa-qq' => '',
							'fa-qrcode' => '',
							'fa-question' => '',
							'fa-question-circle' => '',
							'fa-quote-left' => '',
							'fa-quote-right' => '',
							'fa-ra' => '',
							'fa-random' => '',
							'fa-rebel' => '',
							'fa-recycle' => '',
							'fa-reddit' => '',
							'fa-reddit-square' => '',
							'fa-refresh' => '',
							'fa-renren' => '',
							'fa-reorder' => '',
							'fa-repeat' => '',
							'fa-reply' => '',
							'fa-reply-all' => '',
							'fa-retweet' => '',
							'fa-rmb' => '',
							'fa-road' => '',
							'fa-rocket' => '',
							'fa-rotate-left' => '',
							'fa-rotate-right' => '',
							'fa-rouble' => '',
							'fa-rss' => '',
							'fa-rss-square' => '',
							'fa-rub' => '',
							'fa-ruble' => '',
							'fa-rupee' => '',
							'fa-save' => '',
							'fa-scissors' => '',
							'fa-search' => '',
							'fa-search-minus' => '',
							'fa-search-plus' => '',
							'fa-send' => '',
							'fa-send-o' => '',
							'fa-share' => '',
							'fa-share-alt' => '',
							'fa-share-alt-square' => '',
							'fa-share-square' => '',
							'fa-share-square-o' => '',
							'fa-shield' => '',
							'fa-shopping-cart' => '',
							'fa-sign-in' => '',
							'fa-sign-out' => '',
							'fa-signal' => '',
							'fa-sitemap' => '',
							'fa-skype' => '',
							'fa-slack' => '',
							'fa-sliders' => '',
							'fa-smile-o' => '',
							'fa-sort' => '',
							'fa-sort-alpha-asc' => '',
							'fa-sort-alpha-desc' => '',
							'fa-sort-amount-asc' => '',
							'fa-sort-amount-desc' => '',
							'fa-sort-asc' => '',
							'fa-sort-desc' => '',
							'fa-sort-down' => '',
							'fa-sort-numeric-asc' => '',
							'fa-sort-numeric-desc' => '',
							'fa-sort-up' => '',
							'fa-soundcloud' => '',
							'fa-space-shuttle' => '',
							'fa-spinner' => '',
							'fa-spoon' => '',
							'fa-spotify' => '',
							'fa-square' => '',
							'fa-square-o' => '',
							'fa-stack-exchange' => '',
							'fa-stack-overflow' => '',
							'fa-star' => '',
							'fa-star-half' => '',
							'fa-star-half-empty' => '',
							'fa-star-half-full' => '',
							'fa-star-half-o' => '',
							'fa-star-o' => '',
							'fa-steam' => '',
							'fa-steam-square' => '',
							'fa-step-backward' => '',
							'fa-step-forward' => '',
							'fa-stethoscope' => '',
							'fa-stop' => '',
							'fa-strikethrough' => '',
							'fa-stumbleupon' => '',
							'fa-stumbleupon-circle' => '',
							'fa-subscript' => '',
							'fa-suitcase' => '',
							'fa-sun-o' => '',
							'fa-superscript' => '',
							'fa-support' => '',
							'fa-table' => '',
							'fa-tablet' => '',
							'fa-tachometer' => '',
							'fa-tag' => '',
							'fa-tags' => '',
							'fa-tasks' => '',
							'fa-taxi' => '',
							'fa-tencent-weibo' => '',
							'fa-terminal' => '',
							'fa-text-height' => '',
							'fa-text-width' => '',
							'fa-th' => '',
							'fa-th-large' => '',
							'fa-th-list' => '',
							'fa-thumb-tack' => '',
							'fa-thumbs-down' => '',
							'fa-thumbs-o-down' => '',
							'fa-thumbs-o-up' => '',
							'fa-thumbs-up' => '',
							'fa-ticket' => '',
							'fa-times' => '',
							'fa-times-circle' => '',
							'fa-times-circle-o' => '',
							'fa-tint' => '',
							'fa-toggle-down' => '',
							'fa-toggle-left' => '',
							'fa-toggle-right' => '',
							'fa-toggle-up' => '',
							'fa-trash-o' => '',
							'fa-tree' => '',
							'fa-trello' => '',
							'fa-trophy' => '',
							'fa-truck' => '',
							'fa-try' => '',
							'fa-tumblr' => '',
							'fa-tumblr-square' => '',
							'fa-turkish-lira' => '',
							'fa-twitter' => '',
							'fa-twitter-square' => '',
							'fa-umbrella' => '',
							'fa-underline' => '',
							'fa-undo' => '',
							'fa-university' => '',
							'fa-unlink' => '',
							'fa-unlock' => '',
							'fa-unlock-alt' => '',
							'fa-unsorted' => '',
							'fa-upload' => '',
							'fa-usd' => '',
							'fa-user' => '',
							'fa-user-md' => '',
							'fa-users' => '',
							'fa-video-camera' => '',
							'fa-vimeo-square' => '',
							'fa-vine' => '',
							'fa-vk' => '',
							'fa-volume-down' => '',
							'fa-volume-off' => '',
							'fa-volume-up' => '',
							'fa-warning' => '',
							'fa-wechat' => '',
							'fa-weibo' => '',
							'fa-weixin' => '',
							'fa-wheelchair' => '',
							'fa-windows' => '',
							'fa-won' => '',
							'fa-wordpress' => '',
							'fa-wrench' => '',
							'fa-xing' => '',
							'fa-xing-square' => '',
							'fa-yahoo' => '',
							'fa-yen' => '',
							'fa-youtube' => '',
							'fa-youtube-play' => '',
							'fa-youtube-square' => '',
						),
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add new icon',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-header',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-settings',
		'title' => 'Portfolio Settings',
		'fields' => array (
			array (
				'key' => 'field_555a5775c203b',
				'label' => 'Portfolio Category',
				'name' => 'portfolio_category',
				'type' => 'taxonomy',
				'instructions' => 'Select the category where you want to get the posts.',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_555a579608ced',
				'label' => 'Enable Masonry',
				'name' => 'masonry',
				'type' => 'true_false',
				'message' => 'Enable Masonry',
				'default_value' => 0,
			),
			array (
				'key' => 'field_555a57be244dc',
				'label' => 'Page layout',
				'name' => 'page_layout',
				'type' => 'select',
				'instructions' => 'Choose how many columns you want, default is 3 Columns.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555a579608ced',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					1 => '2 Columns',
					2 => '3 Columns',
					3 => '4 Columns',
				),
				'default_value' => 2,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-portfolio.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-type',
		'title' => 'Post Type',
		'fields' => array (
			array (
				'key' => 'field_555b4b3cf513e',
				'label' => 'Portfolio Post',
				'name' => 'post_type',
				'type' => 'true_false',
				'message' => 'Portfolio Post',
				'default_value' => 0,
			),
			array (
				'key' => 'field_555b4b972f379',
				'label' => 'Image',
				'name' => 'single_background_portfolio_fixed',
				'type' => 'image',
				'instructions' => 'Parallax full height background image in the top.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555b4b3cf513e',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_555b4bf684d84',
				'label' => 'Gallery',
				'name' => 'single_project_portfolio_gallery',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_555b4b3cf513e',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_555b4c0984d85',
						'label' => 'Image',
						'name' => 'single_project_portfolio_gallery_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add an image',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_services-settings',
		'title' => 'Services Settings',
		'fields' => array (
			array (
				'key' => 'field_555a56bb7fbc2',
				'label' => 'Image',
				'name' => 'services_background_image',
				'type' => 'image',
				'instructions' => 'Background image behind the page.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_555a56d47fbc3',
				'label' => 'Content Alignment',
				'name' => 'services_alignment',
				'type' => 'radio',
				'instructions' => 'Choose where you want your content, left or right. Right is default.',
				'choices' => array (
					1 => 'Right',
					2 => 'Left',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_555a570403de5',
				'label' => 'Color',
				'name' => 'services_background_color',
				'type' => 'color_picker',
				'instructions' => 'If you don\'t want to pickup any image, choose your color',
				'default_value' => '',
			),
			array (
				'key' => 'field_555a571a97e4d',
				'label' => 'Services Posts',
				'name' => 'services_posts',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_555a573797e4e',
						'label' => 'Icon',
						'name' => 'service_icon',
						'type' => 'font-awesome',
						'column_width' => '',
						'default_value' => 'null',
						'save_format' => 'class',
						'allow_null' => 0,
						'enqueue_fa' => 0,
						'choices' => array (
							'fa-adjust' => '',
							'fa-adn' => '',
							'fa-align-center' => '',
							'fa-align-justify' => '',
							'fa-align-left' => '',
							'fa-align-right' => '',
							'fa-ambulance' => '',
							'fa-anchor' => '',
							'fa-android' => '',
							'fa-angle-double-down' => '',
							'fa-angle-double-left' => '',
							'fa-angle-double-right' => '',
							'fa-angle-double-up' => '',
							'fa-angle-down' => '',
							'fa-angle-left' => '',
							'fa-angle-right' => '',
							'fa-angle-up' => '',
							'fa-apple' => '',
							'fa-archive' => '',
							'fa-arrow-circle-down' => '',
							'fa-arrow-circle-left' => '',
							'fa-arrow-circle-o-down' => '',
							'fa-arrow-circle-o-left' => '',
							'fa-arrow-circle-o-right' => '',
							'fa-arrow-circle-o-up' => '',
							'fa-arrow-circle-right' => '',
							'fa-arrow-circle-up' => '',
							'fa-arrow-down' => '',
							'fa-arrow-left' => '',
							'fa-arrow-right' => '',
							'fa-arrow-up' => '',
							'fa-arrows' => '',
							'fa-arrows-alt' => '',
							'fa-arrows-h' => '',
							'fa-arrows-v' => '',
							'fa-asterisk' => '',
							'fa-automobile' => '',
							'fa-backward' => '',
							'fa-ban' => '',
							'fa-bank' => '',
							'fa-bar-chart-o' => '',
							'fa-barcode' => '',
							'fa-bars' => '',
							'fa-beer' => '',
							'fa-behance' => '',
							'fa-behance-square' => '',
							'fa-bell' => '',
							'fa-bell-o' => '',
							'fa-bitbucket' => '',
							'fa-bitbucket-square' => '',
							'fa-bitcoin' => '',
							'fa-bold' => '',
							'fa-bolt' => '',
							'fa-bomb' => '',
							'fa-book' => '',
							'fa-bookmark' => '',
							'fa-bookmark-o' => '',
							'fa-briefcase' => '',
							'fa-btc' => '',
							'fa-bug' => '',
							'fa-building' => '',
							'fa-building-o' => '',
							'fa-bullhorn' => '',
							'fa-bullseye' => '',
							'fa-cab' => '',
							'fa-calendar' => '',
							'fa-calendar-o' => '',
							'fa-camera' => '',
							'fa-camera-retro' => '',
							'fa-car' => '',
							'fa-caret-down' => '',
							'fa-caret-left' => '',
							'fa-caret-right' => '',
							'fa-caret-square-o-down' => '',
							'fa-caret-square-o-left' => '',
							'fa-caret-square-o-right' => '',
							'fa-caret-square-o-up' => '',
							'fa-caret-up' => '',
							'fa-certificate' => '',
							'fa-chain' => '',
							'fa-chain-broken' => '',
							'fa-check' => '',
							'fa-check-circle' => '',
							'fa-check-circle-o' => '',
							'fa-check-square' => '',
							'fa-check-square-o' => '',
							'fa-chevron-circle-down' => '',
							'fa-chevron-circle-left' => '',
							'fa-chevron-circle-right' => '',
							'fa-chevron-circle-up' => '',
							'fa-chevron-down' => '',
							'fa-chevron-left' => '',
							'fa-chevron-right' => '',
							'fa-chevron-up' => '',
							'fa-child' => '',
							'fa-circle' => '',
							'fa-circle-o' => '',
							'fa-circle-o-notch' => '',
							'fa-circle-thin' => '',
							'fa-clipboard' => '',
							'fa-clock-o' => '',
							'fa-cloud' => '',
							'fa-cloud-download' => '',
							'fa-cloud-upload' => '',
							'fa-cny' => '',
							'fa-code' => '',
							'fa-code-fork' => '',
							'fa-codepen' => '',
							'fa-coffee' => '',
							'fa-cog' => '',
							'fa-cogs' => '',
							'fa-columns' => '',
							'fa-comment' => '',
							'fa-comment-o' => '',
							'fa-comments' => '',
							'fa-comments-o' => '',
							'fa-compass' => '',
							'fa-compress' => '',
							'fa-copy' => '',
							'fa-credit-card' => '',
							'fa-crop' => '',
							'fa-crosshairs' => '',
							'fa-css3' => '',
							'fa-cube' => '',
							'fa-cubes' => '',
							'fa-cut' => '',
							'fa-cutlery' => '',
							'fa-dashboard' => '',
							'fa-database' => '',
							'fa-dedent' => '',
							'fa-delicious' => '',
							'fa-desktop' => '',
							'fa-deviantart' => '',
							'fa-digg' => '',
							'fa-dollar' => '',
							'fa-dot-circle-o' => '',
							'fa-download' => '',
							'fa-dribbble' => '',
							'fa-dropbox' => '',
							'fa-drupal' => '',
							'fa-edit' => '',
							'fa-eject' => '',
							'fa-ellipsis-h' => '',
							'fa-ellipsis-v' => '',
							'fa-empire' => '',
							'fa-envelope' => '',
							'fa-envelope-o' => '',
							'fa-envelope-square' => '',
							'fa-eraser' => '',
							'fa-eur' => '',
							'fa-euro' => '',
							'fa-exchange' => '',
							'fa-exclamation' => '',
							'fa-exclamation-circle' => '',
							'fa-exclamation-triangle' => '',
							'fa-expand' => '',
							'fa-external-link' => '',
							'fa-external-link-square' => '',
							'fa-eye' => '',
							'fa-eye-slash' => '',
							'fa-facebook' => '',
							'fa-facebook-square' => '',
							'fa-fast-backward' => '',
							'fa-fast-forward' => '',
							'fa-fax' => '',
							'fa-female' => '',
							'fa-fighter-jet' => '',
							'fa-file' => '',
							'fa-file-archive-o' => '',
							'fa-file-audio-o' => '',
							'fa-file-code-o' => '',
							'fa-file-excel-o' => '',
							'fa-file-image-o' => '',
							'fa-file-movie-o' => '',
							'fa-file-o' => '',
							'fa-file-pdf-o' => '',
							'fa-file-photo-o' => '',
							'fa-file-picture-o' => '',
							'fa-file-powerpoint-o' => '',
							'fa-file-sound-o' => '',
							'fa-file-text' => '',
							'fa-file-text-o' => '',
							'fa-file-video-o' => '',
							'fa-file-word-o' => '',
							'fa-file-zip-o' => '',
							'fa-files-o' => '',
							'fa-film' => '',
							'fa-filter' => '',
							'fa-fire' => '',
							'fa-fire-extinguisher' => '',
							'fa-flag' => '',
							'fa-flag-checkered' => '',
							'fa-flag-o' => '',
							'fa-flash' => '',
							'fa-flask' => '',
							'fa-flickr' => '',
							'fa-floppy-o' => '',
							'fa-folder' => '',
							'fa-folder-o' => '',
							'fa-folder-open' => '',
							'fa-folder-open-o' => '',
							'fa-font' => '',
							'fa-forward' => '',
							'fa-foursquare' => '',
							'fa-frown-o' => '',
							'fa-gamepad' => '',
							'fa-gavel' => '',
							'fa-gbp' => '',
							'fa-ge' => '',
							'fa-gear' => '',
							'fa-gears' => '',
							'fa-gift' => '',
							'fa-git' => '',
							'fa-git-square' => '',
							'fa-github' => '',
							'fa-github-alt' => '',
							'fa-github-square' => '',
							'fa-gittip' => '',
							'fa-glass' => '',
							'fa-globe' => '',
							'fa-google' => '',
							'fa-google-plus' => '',
							'fa-google-plus-square' => '',
							'fa-graduation-cap' => '',
							'fa-group' => '',
							'fa-h-square' => '',
							'fa-hacker-news' => '',
							'fa-hand-o-down' => '',
							'fa-hand-o-left' => '',
							'fa-hand-o-right' => '',
							'fa-hand-o-up' => '',
							'fa-hdd-o' => '',
							'fa-header' => '',
							'fa-headphones' => '',
							'fa-heart' => '',
							'fa-heart-o' => '',
							'fa-history' => '',
							'fa-home' => '',
							'fa-hospital-o' => '',
							'fa-html5' => '',
							'fa-image' => '',
							'fa-inbox' => '',
							'fa-indent' => '',
							'fa-info' => '',
							'fa-info-circle' => '',
							'fa-inr' => '',
							'fa-instagram' => '',
							'fa-institution' => '',
							'fa-italic' => '',
							'fa-joomla' => '',
							'fa-jpy' => '',
							'fa-jsfiddle' => '',
							'fa-key' => '',
							'fa-keyboard-o' => '',
							'fa-krw' => '',
							'fa-language' => '',
							'fa-laptop' => '',
							'fa-leaf' => '',
							'fa-legal' => '',
							'fa-lemon-o' => '',
							'fa-level-down' => '',
							'fa-level-up' => '',
							'fa-life-bouy' => '',
							'fa-life-ring' => '',
							'fa-life-saver' => '',
							'fa-lightbulb-o' => '',
							'fa-link' => '',
							'fa-linkedin' => '',
							'fa-linkedin-square' => '',
							'fa-linux' => '',
							'fa-list' => '',
							'fa-list-alt' => '',
							'fa-list-ol' => '',
							'fa-list-ul' => '',
							'fa-location-arrow' => '',
							'fa-lock' => '',
							'fa-long-arrow-down' => '',
							'fa-long-arrow-left' => '',
							'fa-long-arrow-right' => '',
							'fa-long-arrow-up' => '',
							'fa-magic' => '',
							'fa-magnet' => '',
							'fa-mail-forward' => '',
							'fa-mail-reply' => '',
							'fa-mail-reply-all' => '',
							'fa-male' => '',
							'fa-map-marker' => '',
							'fa-maxcdn' => '',
							'fa-medkit' => '',
							'fa-meh-o' => '',
							'fa-microphone' => '',
							'fa-microphone-slash' => '',
							'fa-minus' => '',
							'fa-minus-circle' => '',
							'fa-minus-square' => '',
							'fa-minus-square-o' => '',
							'fa-mobile' => '',
							'fa-mobile-phone' => '',
							'fa-money' => '',
							'fa-moon-o' => '',
							'fa-mortar-board' => '',
							'fa-music' => '',
							'fa-navicon' => '',
							'fa-openid' => '',
							'fa-outdent' => '',
							'fa-pagelines' => '',
							'fa-paper-plane' => '',
							'fa-paper-plane-o' => '',
							'fa-paperclip' => '',
							'fa-paragraph' => '',
							'fa-paste' => '',
							'fa-pause' => '',
							'fa-paw' => '',
							'fa-pencil' => '',
							'fa-pencil-square' => '',
							'fa-pencil-square-o' => '',
							'fa-phone' => '',
							'fa-phone-square' => '',
							'fa-photo' => '',
							'fa-picture-o' => '',
							'fa-pied-piper' => '',
							'fa-pied-piper-alt' => '',
							'fa-pied-piper-square' => '',
							'fa-pinterest' => '',
							'fa-pinterest-square' => '',
							'fa-plane' => '',
							'fa-play' => '',
							'fa-play-circle' => '',
							'fa-play-circle-o' => '',
							'fa-plus' => '',
							'fa-plus-circle' => '',
							'fa-plus-square' => '',
							'fa-plus-square-o' => '',
							'fa-power-off' => '',
							'fa-print' => '',
							'fa-puzzle-piece' => '',
							'fa-qq' => '',
							'fa-qrcode' => '',
							'fa-question' => '',
							'fa-question-circle' => '',
							'fa-quote-left' => '',
							'fa-quote-right' => '',
							'fa-ra' => '',
							'fa-random' => '',
							'fa-rebel' => '',
							'fa-recycle' => '',
							'fa-reddit' => '',
							'fa-reddit-square' => '',
							'fa-refresh' => '',
							'fa-renren' => '',
							'fa-reorder' => '',
							'fa-repeat' => '',
							'fa-reply' => '',
							'fa-reply-all' => '',
							'fa-retweet' => '',
							'fa-rmb' => '',
							'fa-road' => '',
							'fa-rocket' => '',
							'fa-rotate-left' => '',
							'fa-rotate-right' => '',
							'fa-rouble' => '',
							'fa-rss' => '',
							'fa-rss-square' => '',
							'fa-rub' => '',
							'fa-ruble' => '',
							'fa-rupee' => '',
							'fa-save' => '',
							'fa-scissors' => '',
							'fa-search' => '',
							'fa-search-minus' => '',
							'fa-search-plus' => '',
							'fa-send' => '',
							'fa-send-o' => '',
							'fa-share' => '',
							'fa-share-alt' => '',
							'fa-share-alt-square' => '',
							'fa-share-square' => '',
							'fa-share-square-o' => '',
							'fa-shield' => '',
							'fa-shopping-cart' => '',
							'fa-sign-in' => '',
							'fa-sign-out' => '',
							'fa-signal' => '',
							'fa-sitemap' => '',
							'fa-skype' => '',
							'fa-slack' => '',
							'fa-sliders' => '',
							'fa-smile-o' => '',
							'fa-sort' => '',
							'fa-sort-alpha-asc' => '',
							'fa-sort-alpha-desc' => '',
							'fa-sort-amount-asc' => '',
							'fa-sort-amount-desc' => '',
							'fa-sort-asc' => '',
							'fa-sort-desc' => '',
							'fa-sort-down' => '',
							'fa-sort-numeric-asc' => '',
							'fa-sort-numeric-desc' => '',
							'fa-sort-up' => '',
							'fa-soundcloud' => '',
							'fa-space-shuttle' => '',
							'fa-spinner' => '',
							'fa-spoon' => '',
							'fa-spotify' => '',
							'fa-square' => '',
							'fa-square-o' => '',
							'fa-stack-exchange' => '',
							'fa-stack-overflow' => '',
							'fa-star' => '',
							'fa-star-half' => '',
							'fa-star-half-empty' => '',
							'fa-star-half-full' => '',
							'fa-star-half-o' => '',
							'fa-star-o' => '',
							'fa-steam' => '',
							'fa-steam-square' => '',
							'fa-step-backward' => '',
							'fa-step-forward' => '',
							'fa-stethoscope' => '',
							'fa-stop' => '',
							'fa-strikethrough' => '',
							'fa-stumbleupon' => '',
							'fa-stumbleupon-circle' => '',
							'fa-subscript' => '',
							'fa-suitcase' => '',
							'fa-sun-o' => '',
							'fa-superscript' => '',
							'fa-support' => '',
							'fa-table' => '',
							'fa-tablet' => '',
							'fa-tachometer' => '',
							'fa-tag' => '',
							'fa-tags' => '',
							'fa-tasks' => '',
							'fa-taxi' => '',
							'fa-tencent-weibo' => '',
							'fa-terminal' => '',
							'fa-text-height' => '',
							'fa-text-width' => '',
							'fa-th' => '',
							'fa-th-large' => '',
							'fa-th-list' => '',
							'fa-thumb-tack' => '',
							'fa-thumbs-down' => '',
							'fa-thumbs-o-down' => '',
							'fa-thumbs-o-up' => '',
							'fa-thumbs-up' => '',
							'fa-ticket' => '',
							'fa-times' => '',
							'fa-times-circle' => '',
							'fa-times-circle-o' => '',
							'fa-tint' => '',
							'fa-toggle-down' => '',
							'fa-toggle-left' => '',
							'fa-toggle-right' => '',
							'fa-toggle-up' => '',
							'fa-trash-o' => '',
							'fa-tree' => '',
							'fa-trello' => '',
							'fa-trophy' => '',
							'fa-truck' => '',
							'fa-try' => '',
							'fa-tumblr' => '',
							'fa-tumblr-square' => '',
							'fa-turkish-lira' => '',
							'fa-twitter' => '',
							'fa-twitter-square' => '',
							'fa-umbrella' => '',
							'fa-underline' => '',
							'fa-undo' => '',
							'fa-university' => '',
							'fa-unlink' => '',
							'fa-unlock' => '',
							'fa-unlock-alt' => '',
							'fa-unsorted' => '',
							'fa-upload' => '',
							'fa-usd' => '',
							'fa-user' => '',
							'fa-user-md' => '',
							'fa-users' => '',
							'fa-video-camera' => '',
							'fa-vimeo-square' => '',
							'fa-vine' => '',
							'fa-vk' => '',
							'fa-volume-down' => '',
							'fa-volume-off' => '',
							'fa-volume-up' => '',
							'fa-warning' => '',
							'fa-wechat' => '',
							'fa-weibo' => '',
							'fa-weixin' => '',
							'fa-wheelchair' => '',
							'fa-windows' => '',
							'fa-won' => '',
							'fa-wordpress' => '',
							'fa-wrench' => '',
							'fa-xing' => '',
							'fa-xing-square' => '',
							'fa-yahoo' => '',
							'fa-yen' => '',
							'fa-youtube' => '',
							'fa-youtube-play' => '',
							'fa-youtube-square' => '',
						),
					),
					array (
						'key' => 'field_555a574097e4f',
						'label' => 'Title',
						'name' => 'service_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_555a574c97e50',
						'label' => 'Content',
						'name' => 'service_content',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add new post',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-services.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_the-qoute',
		'title' => 'The Qoute',
		'fields' => array (
			array (
				'key' => 'field_555a56081ede0',
				'label' => 'Text',
				'name' => 'about_qoute_text',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_555a561b1ede1',
				'label' => 'Author',
				'name' => 'about_qoute_author',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555a564e98c0f',
				'label' => 'Hide Content',
				'name' => 'about_qoute_hide',
				'type' => 'select',
				'instructions' => 'Hide or Show this content, default is Hide.',
				'choices' => array (
					1 => 'Show',
					2 => 'Hide',
				),
				'default_value' => 2,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


 ?>
